### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by bajie264** [Debajyoti0-0/ToriFY#1]
[#] IP      : 114.xxx.xxx.xx                                                  
[#] COUNTRY :                                                           
[#] CITY    : Shanghai                                                       
- - - - - - - - - - - - - - - - - -                                          
[#] IP      : 114.xxx.xxxx                                                  
[#] COUNTRY : a                                                         
[#] CITY    : Shanghai                                                       
- - - - - - - - - - - - - - - - - -                                                                                  
Traceback (most recent call last):                                           
  File "/home/kali/ToriFY/ip_changer.py", line 104, in change_ip_repeatedly  
    ip_change_delay = int(input(COLOR.YELLOW + '\n[?] ' + COLOR.WHITE + 'Change my IP Every '+COLOR.LIGHT_RED + '[SECONDS]' + COLOR.WHITE + ' : '))       
ValueError: invalid literal for int() with base 10: ''                       
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/usr/local/lib/python3.9/dist-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket                                                    
    cnx.do_handshake()                                                       
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1828, in do_handshake                                                                        
    self._raise_ssl_error(self._ssl, result)                                 
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 1559, in _raise_ssl_error                                                                    
    raise SysCallError(-1, "Unexpected EOF")                                 
OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')                             
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 670, in urlopen                                                           
    httplib_response = self._make_request(                                   
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 381, in _make_request                                                     
    self._validate_conn(conn)                                                
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 978, in _validate_conn                                                    
    conn.connect()                                                           
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connection.py", line 362, in connect                                                               
    self.sock = ssl_wrap_socket(                                             
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket                                                        
    return context.wrap_socket(sock, server_hostname=server_hostname)        
  File "/usr/local/lib/python3.9/dist-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket                                                    
    raise ssl.SSLError("bad handshake: %r" % e)                              
ssl.SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)         
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 439, in send                                                                   
    resp = conn.urlopen(                                                     
  File "/usr/local/lib/python3.9/dist-packages/urllib3/connectionpool.py", line 726, in urlopen                                                           
    retries = retries.increment(                                             
  File "/usr/local/lib/python3.9/dist-packages/urllib3/util/retry.py", line 446, in increment                                                             
    raise MaxRetryError(_pool, url, error or ResponseError(cause))           
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))                           
                                                                             
During handling of the above exception, another exception occurred:          
                                                                             
Traceback (most recent call last):                                           
  File "/home/kali/ToriFY/ip_changer.py", line 323, in <module>              
    Engine()                                                                 
  File "/home/kali/ToriFY/ip_changer.py", line 280, in Engine                
    change_ip_repeatedly()                                                   
  File "/home/kali/ToriFY/ip_changer.py", line 157, in change_ip_repeatedly  
    Engine()                                                                 
  File "/home/kali/ToriFY/ip_changer.py", line 280, in Engine                
    change_ip_repeatedly()                                                   
  File "/home/kali/ToriFY/ip_changer.py", line 141, in change_ip_repeatedly  
    show_ip()                                                                
  File "/home/kali/ToriFY/ip_changer.py", line 84, in show_ip                
    getr = get('https://api.ip.sb/geoip')                                    
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 76, in get                                                                          
    return request('get', url, params=params, **kwargs)                      
  File "/usr/local/lib/python3.9/dist-packages/requests/api.py", line 61, in request                                                                      
    return session.request(method=method, url=url, **kwargs)                 
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 530, in request                                                                
    resp = self.send(prep, **send_kwargs)                                    
  File "/usr/local/lib/python3.9/dist-packages/requests/sessions.py", line 643, in send                                                                   
    r = adapter.send(request, **kwargs)                                      
  File "/usr/local/lib/python3.9/dist-packages/requests/adapters.py", line 514, in send                                                                   
    raise SSLError(e, request=request)                                       
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.ip.sb', port=443): Max retries exceeded with url: /geoip (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

**Comment by iiasceri** [comment]
ye its unfinished

**Comment by Debajyoti0-0** [comment]
Now it is fixed.

Thanks for reporting.
